export enum AccountType {
  CUSTOMER = "CUSTOMER",
  TUTOR = "TUTOR",
}

export enum REQUIRED_GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  NOT_REQUIRED = "NOT_REQUIRED",
}
export enum SUBJECT {
  MATH = "MATH",
  ENGLISH = "ENGLISH",
  LITERATURE = "LITERATURE",
  HISTORY = "HISTORY",
  PHYSICS = "PHYSICS",
  CHEMISTRY = "CHEMISTRY",
  BIOLOGY = "BIOLOGY",
  GEOGRAPHY = "GEOGRAPHY",
  ART = "ART",
  PHILOSOPHY = "PHILOSOPHY",
  RELIGION = "RELIGION",
  ECONOMICS = "ECONOMICS",
}
export enum TEACHING_METHOD {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  ONLINE_AND_OFFLINE = "ONLINE_AND_OFFLINE",
}
