export enum REQUIRED_GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
  NOT_REQUIRED = "NOT_REQUIRED",
}

export enum GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}

export enum SUBJECT {
  MATH = "MATH",
  ENGLISH = "ENGLISH",
  LITERATURE = "LITERATURE",
  HISTORY = "HISTORY",
  PHYSICS = "PHYSICS",
  CHEMISTRY = "CHEMISTRY",
  BIOLOGY = "BIOLOGY",
  GEOGRAPHY = "GEOGRAPHY",
  ART = "ART",
  PHILOSOPHY = "PHILOSOPHY",
  RELIGION = "RELIGION",
  ECONOMICS = "ECONOMICS",
}
export enum TEACHING_METHOD {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  ONLINE_AND_OFFLINE = "ONLINE_AND_OFFLINE",
}

export enum TeachingClassType {
  Kindergarten = "KINDERGARTEN",
  Grade1 = "GRADE_1",
  Grade2 = "GRADE_2",
  Grade3 = "GRADE_3",
  Grade4 = "GRADE_4",
  Grade5 = "GRADE_5",
  Grade6 = "GRADE_6",
  Grade7 = "GRADE_7",
  Grade8 = "GRADE_8",
  Grade9 = "GRADE_9",
  Grade10 = "GRADE_10",
  Grade11 = "GRADE_11",
  Grade12 = "GRADE_12",
  CollegeEntranceExamPreparation = "COLLEGE_ENTRANCE_EXAM_PREPARATION",
  EnglishMediumInstruction = "ENGLISH_MEDIUM_INSTRUCTION",
  TeachingAutisticChildren = "TEACHING_AUTISTIC_CHILDREN",
  SpecializedHighSchoolExamPreparation = "SPECIALIZED_HIGH_SCHOOL_EXAM_PREPARATION",
}

export enum ROLES {
  ADMIN = "ADMIN",
  STAFF = "STAFF",
}

export enum TUTOR_PROFILE_STATUS {
  WAIT_FOR_APPROVE = "WAIT_FOR_APPROVE",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum TUTOR_MAJOR {
  PEDAGOGY_MATHEMATICS = "PEDAGOGY_MATHEMATICS",
  PEDAGOGY_CHEMISTRY = "PEDAGOGY_CHEMISTRY",
  PEDAGOGY_ENGLISH = "PEDAGOGY_ENGLISH",
  PEDAGOGY_COMPUTER_SCIENCE = "PEDAGOGY_COMPUTER_SCIENCE",
  PEDAGOGY_LITERATURE = "PEDAGOGY_LITERATURE",
  PEDAGOGY_HISTORY = "PEDAGOGY_HISTORY",
  PEDAGOGY_GEOGRAPHY = "PEDAGOGY_GEOGRAPHY",
  PEDAGOGY_BIOLOGY = "PEDAGOGY_BIOLOGY",
  PEDAGOGY_MUSIC = "PEDAGOGY_MUSIC",
  EARLY_CHILDHOOD_EDUCATION = "EARLY_CHILDHOOD_EDUCATION",
  PEDAGOGY_EARLY_CHILDHOOD = "PEDAGOGY_EARLY_CHILDHOOD",
  ELEMENTARY_EDUCATION = "ELEMENTARY_EDUCATION",
  PEDAGOGY_ELEMENTARY = "PEDAGOGY_ELEMENTARY",
  SPECIAL_EDUCATION = "SPECIAL_EDUCATION",
  ENGLISH_LANGUAGE = "ENGLISH_LANGUAGE",
  BUSINESS_ENGLISH = "BUSINESS_ENGLISH",
  JAPANESE_LANGUAGE = "JAPANESE_LANGUAGE",
  JAPANESE_STUDIES = "JAPANESE_STUDIES",
  PEDAGOGY_CHINESE_LANGUAGE = "PEDAGOGY_CHINESE_LANGUAGE",
  CHINESE_LANGUAGE = "CHINESE_LANGUAGE",
  MATH_COMPUTER_SCIENCE = "MATH_COMPUTER_SCIENCE",
  INFORMATION_TECHNOLOGY = "INFORMATION_TECHNOLOGY",
  ACCOUNTING = "ACCOUNTING",
  AUDIT = "AUDIT",
  ACCOUNTING_AUDIT = "ACCOUNTING_AUDIT",
  FINANCE_BANKING = "FINANCE_BANKING",
  BUSINESS_MANAGEMENT = "BUSINESS_MANAGEMENT",
  KOREAN_LANGUAGE = "KOREAN_LANGUAGE",
  RUSSIAN_LANGUAGE = "RUSSIAN_LANGUAGE",
  PEDAGOGY_RUSSIAN_LANGUAGE = "PEDAGOGY_RUSSIAN_LANGUAGE",
  FRENCH_LANGUAGE = "FRENCH_LANGUAGE",
  PEDAGOGY_FRENCH_LANGUAGE = "PEDAGOGY_FRENCH_LANGUAGE",
  FOREIGN_LANGUAGES = "FOREIGN_LANGUAGES",
}

export enum NOTIFICATION_STATUS {
  UNREAD = "UNREAD",
  READ = "READ",
}
